---

- name: Get UID of the dovenull user
  ansible.builtin.getent:
    database: passwd
    key: "{{ dovecot_mailowner_user }}"

- name: Get GID of the dovenull user
  ansible.builtin.getent:
    database: group
    key: "{{ dovecot_mailowner_group }}"

- name: Set dovenull UID and GID facts
  ansible.builtin.set_fact:
    dovecot_dovenull_uid: "{{ ansible_facts.getent_passwd[dovecot_mailowner_user][1] }}"
    dovecot_dovenull_gid: "{{ ansible_facts.getent_group[dovecot_mailowner_group][1] }}"

- name: Render base dovecot config
  ansible.builtin.template:
    src: "etc/dovecot/dovecot.conf.j2"
    dest: "/etc/dovecot/dovecot.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart dovecot

- name: Create /etc/dovecot/conf.d
  ansible.builtin.file:
    path: /etc/dovecot/conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Render dovecot conf.d config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/dovecot/conf.d/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart dovecot
  with_fileglob:
    - "templates/etc/dovecot/conf.d/*"

- name: Render dovecot conf.ext config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/dovecot/{{ item | basename }}"
    owner: root
    group: dovecot
    mode: "0640"
  notify: restart dovecot
  with_fileglob:
    - "templates/etc/dovecot/conf.ext/*"

- name: Render master passdb
  ansible.builtin.template:
    src: "etc/dovecot/master-users.j2"
    dest: "{{ dovecot_auth_master_filename }}"
    owner: root
    group: dovecot
    mode: "0640"
  notify: restart dovecot

- name: Render quota warning script
  ansible.builtin.template:
    src: "usr/local/bin/dovecot-quota-warning.sh.j2"
    dest: "/usr/local/bin/dovecot-quota-warning.sh"
    owner: root
    group: dovecot
    mode: "0755"

- name: Create virtual directories
  ansible.builtin.file:
    path: "/etc/dovecot/virtual/{{ item.key }}"
    state: directory
    owner: dovecot
    group: dovecot
    mode: "0755"
  loop: "{{ dovecot_virtual_folders | dict2items }}"
  when: dovecot_virtual_enabled

- name: Render dovecot-virtual file
  ansible.builtin.template:
    src: etc/dovecot/virtual/dovecot-virtual.j2
    dest: "/etc/dovecot/virtual/{{ item.key }}/dovecot-virtual"
    owner: dovecot
    group: dovecot
    mode: "0644"
  vars:
    virtual_folder: "{{ item.value }}"
  loop: "{{ dovecot_virtual_folders | dict2items }}"
  when: dovecot_virtual_enabled

- name: Start and enable dovecot
  ansible.builtin.service:
    name: dovecot
    state: started
    enabled: true

- name: set sysctl variables
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-dovecot.conf
  loop: "{{ dovecot_sysctl | dict2items }}"
