---

- name: Install Dovecot
  ansible.builtin.import_tasks: install.yml
  tags:
    - "role::dovecot"
    - "role::dovecot:install"

- name: Render Dovecot configuration
  ansible.builtin.import_tasks: config.yml
  tags:
    - "role::dovecot"
    - "role::dovecot:config"

- name: Render global Sieve scripts
  ansible.builtin.import_tasks: sieve.yml
  tags:
    - "role::dovecot"
    - "role::dovecot:sieve"

- name: Fetch OIDC JWK keys from IdP for local validation
  ansible.builtin.import_tasks: oidckeys.yml
  tags:
    - "role::dovecot"
    - "role::dovecot:oidckeys"
