---

- name: Create sieve script directories
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: root
    group: "{{ dovecot_mailowner_group }}"
    mode: "0755"
  loop: "{{ dovecot_sieve_scripts }}"

- name: Render sieve scripts
  ansible.builtin.template:
    src: "templates/sieve/{{ item }}"
    dest: "{{ item }}"
    owner: root
    group: "{{ dovecot_mailowner_group }}"
    mode: "0644"
  loop: "{{ dovecot_sieve_scripts }}"

- name: Compile sieve scripts
  ansible.builtin.command: >-
    /usr/bin/sievec {{ item }}
  changed_when: true
  loop: "{{ dovecot_sieve_scripts }}"
