---

dovecot_version: "2.3"
dovecot_repo_version: >-
  {%- if dovecot_version | split('.') | length > 2 -%}ce-{{ dovecot_version }}{%- else -%}ce-latest-{{ dovecot_version }}{% endif %}
dovecot_repository: >-
  deb https://repo.dovecot.org/{{ dovecot_repo_version }}/debian/{{ ansible_facts.distribution_release }} {{ ansible_facts.distribution_release }} main

dovecot_mailowner_user: dovenull
dovecot_mailowner_group: dovenull

dovecot_packages:
  - dovecot-core
  - dovecot-imapd

dovecot_ssl_cert_filename: null
dovecot_ssl_key_filename: null
dovecot_ssl_key_password: null
dovecot_ssl_enabled: "{{ dovecot_ssl_cert_filename is not none or dovecot_ssl_key_filename is not none }}"
dovecot_ssl_min_protocol: TLSv1.2
dovecot_ssl_cipher_list: >-
  ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

dovecot_first_valid_uid: 500
dovecot_last_valid_uid: 0
dovecot_first_valid_gid: 1
dovecot_last_valid_gid: 0


dovecot_mail_location: "mbox:~/mail:INBOX=/var/mail/%u"
dovecot_mail_home: ""
dovecot_mail_uid: ""
dovecot_mail_gid: ""
dovecot_mail_privileged_group: ""
dovecot_namespaces:
  - name: inbox
    inbox: true
    mailboxes:
      Drafts:
        special_use: Drafts
      Junk:
        special_use: Junk
      Trash:
        special_use: Trash
      Sent:
        special_use: Sent
      Sent Messages:
        special_use: Sent

dovecot_default_process_limit: 100
dovecot_default_client_limit: 1000
dovecot_default_vsz_limit: 256M
dovecot_imap_login_service_count: 1
dovecot_imap_login_min_avail: 0
dovecot_imap_login_vsz_limit: "{{ dovecot_default_vsz_limit }}"
dovecot_imap_login_client_limit: "{{ dovecot_default_client_limit }}"
dovecot_pop3_login_service_count: 1
dovecot_pop3_login_min_avail: 0
dovecot_pop3_login_vsz_limit: "{{ dovecot_default_vsz_limit }}"
dovecot_pop3_login_client_limit: "{{ dovecot_default_client_limit }}"
dovecot_imap_vsz_limit: "{{ dovecot_default_vsz_limit }}"
dovecot_imap_process_limit: 1024
dovecot_pop3_vsz_limit: "{{ dovecot_default_vsz_limit }}"
dovecot_pop3_process_limit: 1024
dovecot_auth_worker_service_count: 1
dovecot_auth_client_limit: "{{ dovecot_default_client_limit }}"
dovecot_anvil_client_limit: "{{ dovecot_default_client_limit }}"
dovecot_managesieve_login_service_count: 1
dovecot_managesieve_login_min_avail: 0
dovecot_managesieve_login_vsz_limit: "64M"
dovecot_managesieve_process_limit: 1024
dovecot_managesieve_vsz_limit: "{{ dovecot_default_vsz_limit }}"
dovecot_lmtp_vsz_limit: "{{ dovecot_default_vsz_limit }}"

dovecot_director_enabled: false
dovecot_director_enabled_imap: "{{ dovecot_director_enabled }}"
dovecot_director_enabled_pop3: "{{ dovecot_director_enabled }}"
dovecot_director_enabled_submission: "{{ dovecot_director_enabled }}"
dovecot_director_enabled_lmtp: "{{ dovecot_director_enabled }}"
dovecot_director_enabled_managesieve: "{{ dovecot_director_enabled }}"
dovecot_director_port: 9090
dovecot_director_servers: []
dovecot_director_mail_servers: []
dovecot_director_user_expire: "15 min"
dovecot_director_username_hash: "%Lu"
dovecot_lmtp_proxy: false

dovecot_login_trusted_networks: []

dovecot_enable_postfix_auth_service: false
dovecot_disable_plaintext_auth: true
dovecot_auth_cache_size: 0
dovecot_auth_cache_ttl: 1 hour
dovecot_auth_cache_negative_ttl: 1 hour
dovecot_auth_master_user_separator: ""
dovecot_auth_enabled:
  - system
dovecot_auth_mechanisms:
  - login
  - plain

dovecot_auth_static_passdb_args: ["proxy=y", "nopassword=y"]

dovecot_auth_master_filename: /etc/dovecot/master-users
dovecot_auth_master_users: {}

dovecot_auth_ldap_uri: ldapi:///run/slapd/ldapi
dovecot_auth_ldap_bind_dn: ""
dovecot_auth_ldap_bind_pass: ""
dovecot_auth_ldap_search_base: ""
dovecot_auth_ldap_user_attrs: ["homeDirectory=home", "uidNumber=uid", "gidNumber=gid"]
dovecot_auth_ldap_user_filter: "(&(objectClass=posixAccount)(uid=%u))"
dovecot_auth_ldap_pass_attrs: ["uid=user", "userPassword=password"]
dovecot_auth_ldap_pass_filter: "(&(objectClass=posixAccount)(uid=%u))"
dovecot_auth_ldap_iterate_attrs: ["uid=user"]
dovecot_auth_ldap_iterate_filter: "(objectClass=posixAccount)"

dovecot_auth_oauth2_tokeninfo_url: ""
dovecot_auth_oauth2_username_attribute: email
dovecot_oidc_azp:
  - default

dovecot_imap_mail_max_userip_connections: 10

dovecot_lmtp_bind_inet: false
dovecot_lmtp_bind_port: 24
dovecot_submission_host: ""

dovecot_acl_enabled: false
dovecot_acl_imap_enabled: "{{ dovecot_acl_enabled }}"
dovecot_acl: []
dovecot_acl_shared_dict: ""
dovecot_acl_anyone: false
dovecot_acl_user: ""

dovecot_quota_enabled: false
dovecot_quota_imap_enabled: "{{ dovecot_quota_enabled }}"
dovecot_quota_roots: ["maildir:User quota"]
dovecot_quota_rules:
  - "*:storage=1G"
  - "Trash:storage=+100M"
dovecot_quota_warning_script: null
dovecot_quota_warning_executable_user: dovecot
dovecot_quota_warning_socket_user: vmail
dovecot_quota_warnings: []

dovecot_push_notification_enabled: false
dovecot_push_notification_driver: ""

dovecot_sieve_enabled: false
dovecot_sieve_lmtp_enabled: "{{ dovecot_sieve_enabled }}"
dovecot_sieve_lda_enabled: "{{ dovecot_sieve_enabled }}"
dovecot_sieve_mail_max_userip_connections: 10
dovecot_sieve_global_dirname: ""
dovecot_sieve_before: []
dovecot_sieve_scripts: []

dovecot_pop3_client_workarounds: []

dovecot_additional_config: ""
